# Jekyll configuration for GitHub Pages
plugins:
  - jekyll-redirect-from

# Enable clean URLs (remove .html extension)
permalink: pretty

# Include files that start with underscore
include:
  - _config.yml

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
